"""Live trading configuration models and defaults.

This module defines configuration dataclasses for live (real-time or daily) trading
workflow stages: data ingestion, portfolio construction, risk management, execution,
monitoring & persistence.

Separate from backtest `SystemConfig` to avoid accidental coupling; only minimal,
serializable fields for scheduling & ops.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional, Dict


@dataclass
class DataIngestionConfig:
    data_dir: str = "data"
    file_pattern: str = "*.csv"  # prediction files generated by models
    latest_days: int = 1  # how many latest days to load (1 = only today's predictions)
    required_columns: List[str] = field(default_factory=lambda: ["date", "code", "weight"])  # base schema
    allow_missing_weight: bool = True  # if True, default weight=1.0 when absent
    normalize_codes: bool = True


@dataclass
class PortfolioConfig:
    top_n: int = 30
    max_stock_weight: float = 0.10
    max_industry_weight: float = 0.35
    min_weight_threshold: float = 0.001  # weights below are truncated to zero before renorm
    rebalance_days: int = 3  # similar to hold_days; only rebuild if due or drift large
    turnover_threshold: float = 0.15  # if predicted target vs current causes turnover > threshold, skip partial
    industry_map_file: Optional[str] = "config/industry_category.csv"


@dataclass
class RiskConfig:
    max_drawdown_limit: float = 0.08  # trigger de-risk (partial to cash)
    circuit_break_drawdown: float = 0.12  # trigger full cash liquidation
    volatility_target: float = 0.20  # annualized target
    vol_lookback: int = 20
    concentration_hhi_limit: float = 0.18  # Herfindahl index limit
    ic_rolling_window: int = 20  # for drift detector
    min_ic_threshold: float = 0.02  # below this means predictive power questionable


@dataclass
class ExecutionConfig:
    simulate: bool = True  # if False, send real orders through adapter
    lot_size: int = 100  # round shares to nearest lot
    max_slippage_bp: int = 30  # basis points tolerated
    price_source: str = "akshare"  # placeholder for real-time price source
    parallel_orders: int = 10  # concurrency for order dispatch


@dataclass
class PersistenceConfig:
    state_dir: str = "live_state"  # where we store positions, nav, audit logs
    nav_file: str = "nav.csv"
    position_file: str = "positions.csv"
    audit_file: str = "audit.log"
    drift_file: str = "drift_metrics.csv"


@dataclass
class MonitoringConfig:
    enable_metrics: bool = True
    metrics_sink: str = "stdout"  # could be 'prometheus', 'influx', etc.
    alert_channel: Optional[str] = None  # e.g. webhook url
    alert_drawdown: float = 0.10
    alert_slippage_bp: int = 50


@dataclass
class LiveConfig:
    data: DataIngestionConfig = field(default_factory=DataIngestionConfig)
    portfolio: PortfolioConfig = field(default_factory=PortfolioConfig)
    risk: RiskConfig = field(default_factory=RiskConfig)
    execution: ExecutionConfig = field(default_factory=ExecutionConfig)
    persistence: PersistenceConfig = field(default_factory=PersistenceConfig)
    monitoring: MonitoringConfig = field(default_factory=MonitoringConfig)
    extra: Dict[str, str] = field(default_factory=dict)  # place for ad-hoc runtime overrides


DEFAULT_LIVE_CONFIG = LiveConfig()
